// define PID value for the Drive controller

#define DISTANCE_KP 0.5
#define DISTANCE_KI 0.01
#define DISTANCE_KD 0.00

#define ANGLE_KP 0.05
#define ANGLE_KI 0
#define ANGLE_KD 0

#define RADAR_MIN_DISTANCE 200 // mm

#define CHECK_LEFT_RADAR_ON_LEFT_ROTATION 1
#define CHECK_LEFT_RADAR_ON_RIGHT_ROTATION 1
#define CHECK_LEFT_RADAR_ON_FRONT_FORWARD 1

#define CHECK_RIGHT_RADAR_ON_LEFT_ROTATION 1
#define CHECK_RIGHT_RADAR_ON_RIGHT_ROTATION 1
#define CHECK_RIGHT_RADAR_ON_FRONT_FORWARD 1

#define CHECK_FRONT_RADAR_ON_LEFT_ROTATION 0
#define CHECK_FRONT_RADAR_ON_RIGHT_ROTATION 0
#define CHECK_FRONT_RADAR_ON_FRONT_FORWARD 1